apiVersion: apps/v1
kind: Deployment
metadata:
  name: nim-embedding-deployment
  labels:
    app: nim-embedding
spec:
  replicas: 1
  selector:
    matchLabels:
      app: nim-embedding
  template:
    metadata:
      labels:
        app: nim-embedding
    spec:
      nodeSelector:
        cloud.google.com/compute-class: "Accelerator"
        cloud.google.com/gke-accelerator: "nvidia-l4"
      serviceAccountName: default
      containers:
      - name: nim-container
        image: nvcr.io/nim/nvidia/llama-3.2-nv-embedqa-1b-v2:1.3.0
        ports:
        - containerPort: 8000
          name: http-nim
        env:
        - name: NGC_API_KEY
          valueFrom:
            secretKeyRef:
              name: ngc-api-key-secret
              key: NGC_API_KEY
        - name: NIM_MODEL_NAME
          value: /model
        - name: NIM_SERVED_MODEL_NAME
          value: llama-3.2-nv-embedqa-1b-v2
        - name: NIM_CUSTOM_MODEL_NAME
          value: llama-3.2-nv-embedqa-1b-v2
        - name: NIM_ENABLE_KV_CACHE_REUSE
          value: "1"
        resources:
          requests:
            cpu: "2"
            memory: "32Gi"
            nvidia.com/gpu: "1"
          limits:
            nvidia.com/gpu: "1"
        livenessProbe:
          httpGet:
            path: /v1/health/live
            port: http-nim
        readinessProbe:
          httpGet:
            path: /v1/health/ready
            port: http-nim
        startupProbe:
          httpGet:
            path: /v1/health/ready
            port: http-nim
          periodSeconds: 10
          failureThreshold: 180
          initialDelaySeconds: 40
        volumeMounts:
        - mountPath: /opt/nim/.cache
          name: cache-storage
      volumes:
      - name: cache-storage
        emptyDir: {}
---
apiVersion: v1
kind: Service
metadata:
  name: nim-embedding-service
spec:
  selector:
    app: nim-embedding
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: LoadBalancer
